server:
  port: 8189

network: mainnet

chains: [Ethereum,Tron]

wallet_node:
  eth:
    rpcs:
      - rpc_url: 'https://rpc.flashbots.net'
    confirmations: 4
    data_api_url: 'https://api.etherscan.io/api?'
    data_api_key: 'HZEZGEPJJDA633N421AYW9NE8JFNZZC7JT'
    data_api_token: ''
    time_out: 100
  tron:
    rpcs:
      - rpc_url: 'https://docs-demo.tron-mainnet.quiknode.pro'
    confirmations: 4
    data_api_url: ''
    data_api_key: ''
    data_api_token: ''
    time_out: 100
